run:
	@echo "Executando a interface grafica"
	pyuic5.exe .\main.ui -o main.py
	python .\teste.py

all:
	@echo "Executando a interface grafica"
	pyuic5.exe .\main.ui -o main.py
	pyrcc5.exe .\resources.qrc -o resources_rc.py
	python .\teste.py
